# Adds namespace to all resources.
namespace: authorino

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
namePrefix: authorino-

# Labels to add to all resources and selectors.
commonLabels:
  app: authorino

resources:
- api-protections.yaml
- manager.yaml
- rbac.yaml

patchesStrategicMerge:
- manager_patch.yaml
